

delete_t2audit_checklist_new=" DROP TABLE public.t2audit_checklist_new;"
create_t2audit_checklist_new=
    '''
        CREATE TABLE IF NOT EXISTS public.t2audit_checklist_new
        (
            newaudit_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
            date_record character varying(255) COLLATE pg_catalog."default",
            reference character varying(255) COLLATE pg_catalog."default",
            qhestions character varying(255) COLLATE pg_catalog."default",
            required_tobe_reference character varying(255) COLLATE pg_catalog."default",
            inspection_type character varying(255) COLLATE pg_catalog."default",
            following_from_previeos character varying(255) COLLATE pg_catalog."default",
            folloing_to_next character varying(255) COLLATE pg_catalog."default",
            following_tobics character varying(255) COLLATE pg_catalog."default",
            required_from_previews_flow character varying(255) COLLATE pg_catalog."default",
            important_degree character varying(255) COLLATE pg_catalog."default",
            assessment character varying(255) COLLATE pg_catalog."default",
            followupt character varying(255) COLLATE pg_catalog."default",
            nonconformity character varying(255) COLLATE pg_catalog."default",
            ncr_details character varying(255) COLLATE pg_catalog."default",
            industry_type character varying(255) COLLATE pg_catalog."default",
            secotr character varying(255) COLLATE pg_catalog."default",
            department character varying(255) COLLATE pg_catalog."default",
            section character varying(255) COLLATE pg_catalog."default",
            classification character varying(255) COLLATE pg_catalog."default",
            sepc_requirement character varying(255) COLLATE pg_catalog."default",
            procedure_name character varying(255) COLLATE pg_catalog."default",
            are_there_similarity_ncr character varying(255) COLLATE pg_catalog."default",
            decision_for_correct_nce_now character varying(255) COLLATE pg_catalog."default",
            problem_root_cause character varying(255) COLLATE pg_catalog."default",
            root_type character varying(255) COLLATE pg_catalog."default",
            why_non_descover character varying(255) COLLATE pg_catalog."default",
            corrective_action character varying(255) COLLATE pg_catalog."default",
            corrective_action_type character varying(255) COLLATE pg_catalog."default",
            risk character varying(255) COLLATE pg_catalog."default",
            procedure_type character varying(255) COLLATE pg_catalog."default",
            due_date character varying(255) COLLATE pg_catalog."default",
            responsibility character varying(255) COLLATE pg_catalog."default",
            corrective_action_assure character varying(255) COLLATE pg_catalog."default",
            corrective_followup character varying(255) COLLATE pg_catalog."default",
            follower character varying(255) COLLATE pg_catalog."default",
            "1st Review" character varying(255) COLLATE pg_catalog."default",
            "2nd review" character varying(255) COLLATE pg_catalog."default",
            "3d review" character varying(255) COLLATE pg_catalog."default",
            "4d review" character varying(255) COLLATE pg_catalog."default",
            "5d review" character varying(255) COLLATE pg_catalog."default",
            "6d review" character varying(255) COLLATE pg_catalog."default",
            "7d review" character varying(255) COLLATE pg_catalog."default",
            attached_ok text COLLATE pg_catalog."default",
            attachment text COLLATE pg_catalog."default",
            department_discovery character varying(255) COLLATE pg_catalog."default",
            source_ncr character varying(255) COLLATE pg_catalog."default",
            ncr_no character varying(255) COLLATE pg_catalog."default",
            complan_id character varying(255) COLLATE pg_catalog."default",
            preventice_id character varying(255) COLLATE pg_catalog."default",
            audit_id character varying(255) COLLATE pg_catalog."default",
            vedors_audit_id character varying(255) COLLATE pg_catalog."default",
            accident_id character varying(255) COLLATE pg_catalog."default",
            ncr_notes character varying(255) COLLATE pg_catalog."default",
            internal_notes character varying(255) COLLATE pg_catalog."default",
            refernces character varying(255) COLLATE pg_catalog."default",
            link text COLLATE pg_catalog."default",
            palnned_audit character varying(255) COLLATE pg_catalog."default",
            unplaned_audit character varying(255) COLLATE pg_catalog."default",
            CONSTRAINT "qa_auidt_t2checkList_new_pkey" PRIMARY KEY (newaudit_id)
        )
        WITH (
            OIDS = FALSE
        )
        TABLESPACE pg_default;

        ALTER TABLE public.t2audit_checklist_new
            OWNER to postgres;'''



delete_t4hr_persons='''-- DROP TABLE public.t4hr_persons;'''

create_t4hr_persons='''
    "
    CREATE TABLE IF NOT EXISTS public.t4hr_persons
    (
        "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
        name character varying(255) COLLATE pg_catalog."default",
        attendance_id integer,
        department_id integer,
        job_id integer,
        attendance_machine character varying(255) COLLATE pg_catalog."default",
        id_outlook integer,
        CONSTRAINT t4hr_persons_pkey PRIMARY KEY ("ID")
    )
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

    ALTER TABLE public.t4hr_persons
        OWNER to postgres;

    GRANT ALL ON TABLE public.t4hr_persons TO postgres;

    GRANT ALL ON TABLE public.t4hr_persons TO quality;'''