delte_t4hr_persons="DROP TABLE public.t4hr_persons;"
create_t4hr_persons='''
    CREATE TABLE IF NOT EXISTS public.t4hr_persons
    (
        "ID" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
        name character varying(255) COLLATE pg_catalog."default",
        attendance_id integer,
        department_id integer,
        job_id integer,
        attendance_machine character varying(255) COLLATE pg_catalog."default",
        id_outlook integer,
        CONSTRAINT t4hr_persons_pkey PRIMARY KEY ("ID")
    )
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

    ALTER TABLE public.t4hr_persons
        OWNER to postgres;

    GRANT ALL ON TABLE public.t4hr_persons TO postgres;

    GRANT ALL ON TABLE public.t4hr_persons TO quality;
    '''

delete_t5hr_departments=" DROP TABLE public.t5hr_departments;"
create_t5hr_departments='''
    CREATE TABLE IF NOT EXISTS public.t5hr_departments
    (
        "ID_Departments" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
        industry_type character varying(255) COLLATE pg_catalog."default",
        sector character varying(255) COLLATE pg_catalog."default",
        department character varying(255) COLLATE pg_catalog."default",
        section character varying(255) COLLATE pg_catalog."default",
        place character varying(255) COLLATE pg_catalog."default",
        id_sector integer,
        id_place character varying(255) COLLATE pg_catalog."default",
        "functionality-sector" character varying(255) COLLATE pg_catalog."default",
        mother_id integer,
        parent_id integer,
        CONSTRAINT hr_t7departments_pkey PRIMARY KEY ("ID_Departments")
    )
    WITH (
        OIDS = FALSE
    )
    TABLESPACE pg_default;

    ALTER TABLE public.t5hr_departments
        OWNER to postgres;

    GRANT ALL ON TABLE public.t5hr_departments TO postgres;

    GRANT ALL ON TABLE public.t5hr_departments TO quality;
    '''