# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mengx/Desktop/Final Project Test/Manage.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class ManageUser_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(563, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEmail.setGeometry(QtCore.QRect(260, 60, 161, 31))
        self.txtEmail.setObjectName("txtEmail")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 110, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setObjectName("label_2")
        self.txtUser = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUser.setGeometry(QtCore.QRect(260, 20, 161, 31))
        self.txtUser.setObjectName("txtUser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label.setObjectName("label")
        self.txtPass = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPass.setGeometry(QtCore.QRect(260, 180, 161, 31))
        self.txtPass.setObjectName("txtPass")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 190, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_4.setObjectName("label_4")
        self.txtLname = QtWidgets.QLineEdit(self.centralwidget)
        self.txtLname.setGeometry(QtCore.QRect(260, 140, 161, 31))
        self.txtLname.setObjectName("txtLname")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(110, 70, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_6.setObjectName("label_6")
        self.txtFname = QtWidgets.QLineEdit(self.centralwidget)
        self.txtFname.setGeometry(QtCore.QRect(260, 100, 161, 31))
        self.txtFname.setObjectName("txtFname")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_3.setObjectName("label_3")
        self.twgUser = QtWidgets.QTableWidget(self.centralwidget)
        self.twgUser.setGeometry(QtCore.QRect(5, 270, 551, 291))
        self.twgUser.setObjectName("twgUser")
        self.twgUser.setColumnCount(5)
        self.twgUser.setRowCount(0)
        self.twgUser.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        item = QtWidgets.QTableWidgetItem()
        self.twgUser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twgUser.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twgUser.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twgUser.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.twgUser.setHorizontalHeaderItem(4, item)
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(20, 230, 80, 29))
        self.btnAdd.setObjectName("btnAdd")
        self.BtnSave = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSave.setGeometry(QtCore.QRect(360, 230, 80, 29))
        self.BtnSave.setObjectName("BtnSave")
        self.btnRemove = QtWidgets.QPushButton(self.centralwidget)
        self.btnRemove.setGeometry(QtCore.QRect(250, 230, 80, 29))
        self.btnRemove.setObjectName("btnRemove")
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setGeometry(QtCore.QRect(140, 230, 80, 29))
        self.btnEdit.setObjectName("btnEdit")
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(470, 230, 80, 29))
        self.btnCancel.setObjectName("btnCancel")
        MainWindow.setCentralWidget(self.centralwidget)



        ##############################################
        self.txtPass.setEnabled(False)
        self.txtUser.setEnabled(False)
        self.txtEmail.setEnabled(False)
        self.txtFname.setEnabled(False)
        self.txtLname.setEnabled(False)

        
        self.btnEdit.setEnabled(False)
        self.btnRemove.setEnabled(False)
        self.BtnSave.setEnabled(False)
        self.btnAdd.setEnabled(True)
        self.btnCancel.setEnabled(True)

        ##############################################

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ManageUser"))
        self.label_2.setText(_translate("MainWindow", "First Name"))
        self.label.setText(_translate("MainWindow", "Username"))
        self.label_4.setText(_translate("MainWindow", "Password"))
        self.label_6.setText(_translate("MainWindow", "Email"))
        self.label_3.setText(_translate("MainWindow", "Last Name"))
        item = self.twgUser.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.twgUser.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Email"))
        item = self.twgUser.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Lname"))
        item = self.twgUser.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Lname"))
        item = self.twgUser.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Pass"))
        self.btnAdd.setText(_translate("MainWindow", "Add"))
        self.BtnSave.setText(_translate("MainWindow", "Save"))
        self.btnRemove.setText(_translate("MainWindow", "Remove"))
        self.btnEdit.setText(_translate("MainWindow", "Edit"))
        self.btnCancel.setText(_translate("MainWindow", "Cancel"))

